name: zabor
description: A new Flutter application.

publish_to: "none"

version: 1.5.10+00

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  path: ^1.8.1
  lottie: ^1.4.1
  sqflite: ^2.0.2
  provider: ^6.0.2
  geolocator: ^9.0.1
  package_info: ^2.0.2
  # fluttertoast: ^8.0.9
  path_provider: ^2.0.9
  url_launcher: ^6.0.20
  esc_pos_utils: ^1.1.0
  google_sign_in: ^5.2.4
  network_tools: ^3.0.0+2
  esc_pos_printer: ^4.1.0
  #  esc_pos_bluetooth: ^0.4.1
  easy_localization: ^3.0.0
  shared_preferences: ^2.2.3
  flutter_credit_card: ^3.0.1
  flutter_facebook_auth: ^4.1.2
  font_awesome_flutter: ^10.0.0
  #  stripe_terminal: ^1.4.2+2
  sentry_flutter: ^8.3.0
  material_design_icons_flutter: ^5.0.6996
  intl:
  jwt_decode: ^0.3.1
  # stripe_terminal:
  #   path: flutter_stripe_terminal
  collection: ^1.16.0
  http: ^0.13.5
  xml2json: ^5.3.6
  web_socket_channel: ^2.4.0
  blur: ^3.1.0
  pinput: ^5.0.0
  dropdown_button2: ^2.3.9
  permission_handler: ^11.3.1
  file_picker: ^8.0.5

#  flutter_bluetooth_basic: ^0.1.7

dev_dependencies:
  flutter_launcher_icons: ^0.11.0

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpeg"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/translations/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Light.ttf
  #         weight: 400
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 800

  #   - family: Open Sans
  #     fonts:
  #       - asset: assets/fonts/OpenSans-Light.ttf
  #         weight: 400
  #       - asset: assets/fonts/OpenSans-Regular.ttf
  #         weight: 500

  #   - family: Manrope
  #     fonts:
  #       # - asset: assets/fonts/Manrope-Light.ttf
  #       #   weight: 300
  #       - asset: assets/fonts/Manrope-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Manrope-SemiBold.ttf
  #         weight: 500
  #       - asset: assets/fonts/Manrope-Medium.ttf
  #         weight: 600
  #       - asset: assets/fonts/Manrope-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Manrope-ExtraBold.ttf
  #         weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
